jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SONATA_REALESTATE_EDITOR:
            - ROLE_SONATA_ADMIN_REALESTATE_LIST
            - ROLE_SONATA_ADMIN_REALESTATE_VIEW
            - ROLE_SONATA_ADMIN_REALESTATE_CREATE
            - ROLE_SONATA_ADMIN_REALESTATE_EDIT
            - ROLE_SONATA_ADMIN_REALESTATE_EXPORT
            - ROLE_SONATA_ADMIN_CATEGORY_LIST
            - ROLE_SONATA_ADMIN_CATEGORY_VIEW
            - ROLE_SONATA_ADMIN_CATEGORY_CREATE
            - ROLE_SONATA_ADMIN_TYPE_ESTATE_LIST
            - ROLE_SONATA_ADMIN_TYPE_ESTATE_VIEW
            - ROLE_SONATA_ADMIN_TYPE_ESTATE_CREATE
        ROLE_SONATA_ADDRESS_CREATOR:
            - ROLE_SONATA_ADMIN_CITY_LIST
            - ROLE_SONATA_ADMIN_CITY_CREATE
            - ROLE_SONATA_ADMIN_CITY_VIEW
            - ROLE_SONATA_ADMIN_STREET_LIST
            - ROLE_SONATA_ADMIN_STREET_CREATE
            - ROLE_SONATA_ADMIN_STREET_VIEW
            - ROLE_SONATA_ADMIN_REGION_LIST
            - ROLE_SONATA_ADMIN_REGION_CREATE
            - ROLE_SONATA_ADMIN_REGION_VIEW
        ROLE_SONATA_IMAGE_EDITOR:
            - ROLE_SONATA_ADMIN_IMAGE_LIST
            - ROLE_SONATA_ADMIN_IMAGE_VIEW
            - ROLE_SONATA_ADMIN_IMAGE_CREATE
            - ROLE_SONATA_ADMIN_IMAGE_EDIT
        ROLE_SONATA_USER_VIEWER:
            - ROLE_SONATA_ADMIN_USER_VIEW
            - ROLE_SONATA_ADMIN_USER_LIST
        ROLE_AGENT:       [ROLE_SONATA_REALESTATE_EDITOR, ROLE_SONATA_ADDRESS_CREATOR, ROLE_SONATA_IMAGE_EDITOR]
        ROLE_ADMIN:       ROLE_AGENT
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_decision_manager:
            strategy: unanimous

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_AGENT }
