index:
#    pattern:  /
#    defaults: { _controller: RealEstateBundle:Default:index }
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/dashboard
        permanent: true